services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./backend/src/nginx/default.conf:/etc/nginx/conf.d/default.conf

  ecosnap-backend:
    image: nelson254/ecosnap-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    # depends_on:
      # - postgres
    
  # ecosnap-frontend:
  #   image: nelson254/ecosnap-frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - ecosnap-backend


  mongo-database:
    image: mongo
    volumes:
      - ecosnap-mongo-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27019:27017
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ecosnap-redis-volume:/data

  # postgres:
  #   image: postgres:18
  #   restart: always
  #   environment:
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_USER=nelson
  #     - POSTGRES_DB=ecosnap
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ecosnap-postgres-volume:/var/lib/postgresql/18/docker

volumes:
  ecosnap-mongo-volume:
  ecosnap-redis-volume:
  # ecosnap-postgres-volume:
