services:
  nginx:
    ports:
      - 8080:80
    volumes:
      - ./backend/src/nginx/default.conf:/etc/nginx/conf.d/default.conf
  ecosnap-backend:
    build:
      args:
        - NODE_ENV=development
    volumes:
      - ./backend:/app # syncs code on local machine with container code
      - /app/node_modules #Prevents the bind mount from modifying the node_modules in the container
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]

  # ecosnap-frontend:
  #   environment:
  #     - WATCHPACK_POLLING=true
  #     - CHOKIDAR_USEPOLLING=true
  #     - NODE_ENV=development

  #   volumes:
  #     - ./frontend:/frontend
  #     - /frontend/node_modules
  #   command: ["npm", "run","dev"]
